# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface2.0.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1062, 756)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1040, 629))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 158))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 158))
        self.groupBox.setSizeIncrement(QtCore.QSize(0, 158))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(40, 30, 451, 101))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_cantidad_clases = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.btn_cantidad_clases.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_cantidad_clases.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cantidad_clases.setFont(font)
        self.btn_cantidad_clases.setMinimum(1)
        self.btn_cantidad_clases.setMaximum(50)
        self.btn_cantidad_clases.setObjectName("btn_cantidad_clases")
        self.gridLayout_3.addWidget(self.btn_cantidad_clases, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.btn_archivo = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_archivo.setFont(font)
        self.btn_archivo.setObjectName("btn_archivo")
        self.gridLayout_3.addWidget(self.btn_archivo, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 158))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 158))
        self.groupBox_2.setSizeIncrement(QtCore.QSize(0, 158))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 461, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.radiobtn_graficar = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radiobtn_graficar.setFont(font)
        self.radiobtn_graficar.setObjectName("radiobtn_graficar")
        self.gridLayout.addWidget(self.radiobtn_graficar, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dimension_uno = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.dimension_uno.setMinimumSize(QtCore.QSize(50, 30))
        self.dimension_uno.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dimension_uno.setFont(font)
        self.dimension_uno.setMinimum(1)
        self.dimension_uno.setMaximum(50)
        self.dimension_uno.setProperty("value", 1)
        self.dimension_uno.setObjectName("dimension_uno")
        self.horizontalLayout.addWidget(self.dimension_uno)
        self.dimension_dos = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.dimension_dos.setMinimumSize(QtCore.QSize(50, 30))
        self.dimension_dos.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dimension_dos.setFont(font)
        self.dimension_dos.setMinimum(1)
        self.dimension_dos.setMaximum(50)
        self.dimension_dos.setProperty("value", 1)
        self.dimension_dos.setObjectName("dimension_dos")
        self.horizontalLayout.addWidget(self.dimension_dos)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.table = QtWidgets.QTableView(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setMinimumSize(QtCore.QSize(990, 400))
        self.table.setMaximumSize(QtCore.QSize(16777215, 400))
        self.table.setObjectName("table")
        self.verticalLayout.addWidget(self.table)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_clasificar = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_clasificar.setFont(font)
        self.btn_clasificar.setObjectName("btn_clasificar")
        self.horizontalLayout_3.addWidget(self.btn_clasificar)
        self.btn_salir = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_salir.setFont(font)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout_3.addWidget(self.btn_salir)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        self.btn_salir.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Datos de entrada"))
        self.label_2.setText(_translate("Form", "Seleccione cantidad de clases a encontrar"))
        self.btn_archivo.setText(_translate("Form", "..."))
        self.label.setText(_translate("Form", "Seleccione archivo"))
        self.groupBox_2.setTitle(_translate("Form", "Gráfico"))
        self.label_3.setText(_translate("Form", "Dimensiones"))
        self.radiobtn_graficar.setText(_translate("Form", "Graficar"))
        self.btn_clasificar.setText(_translate("Form", "Clasificar"))
        self.btn_salir.setText(_translate("Form", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

